import 'dart:math';

import 'package:dreamtravel/data/booking_data.dart';
import 'package:dreamtravel/data/flight_boarding_data.dart';
import 'package:dreamtravel/data/hotel_booking_data.dart';
import 'package:dreamtravel/data/tour_booking_data.dart';
import 'package:dreamtravel/data/travel_data.dart';
import 'package:flutter/material.dart';

final sampleBookingDataList = [
  BookingData(
    bookingId: Random().nextInt(10000),
    bookingFirstName: "flightBookingName",
    bookingLastName: "flightBookingLocation",
    bookingPrice: 340.00,
    bookingPassengers: 3,
    travelData: TravelData(
      travelId: Random().nextInt(10000),
      travelCity: "Naples",
      travelCountry: "Italy",
      travelStartDate: DateTime.parse("20260912"),
      travelEndDate: DateTime.parse("20261004"),
      travelImageUrl:
          "https://images.unsplash.com/photo-1715702803426-39aa0d4c39a9?&auto=format&fit=crop&q=100&w=1200",
      travelDataHasImage: true,
      travelTotalCost: 200,
      travelBookingIncludesFlight: true,
      travelBookingIncludesHotel: true,
      travelBookingIncludesTour: true,
    ),
    flightBoardingData: sampleFlightBoardingDataList,
    hotelBookingData: sampleHotelBookingDataList,
    tourBookingData: sampleTourBookingDataList,
  ),
  BookingData(
    bookingId: Random().nextInt(10000),
    bookingFirstName: "flightBookingName",
    bookingLastName: "flightBookingLocation",
    bookingPrice: 340.00,
    bookingPassengers: 3,
    travelData: TravelData(
      travelId: Random().nextInt(10000),
      travelCity: "Naples",
      travelCountry: "Italy",
      travelStartDate: DateTime.parse("20260912"),
      travelEndDate: DateTime.parse("20261004"),
      travelImageUrl:
          "https://images.unsplash.com/photo-1715702803426-39aa0d4c39a9?&auto=format&fit=crop&q=100&w=1200",
      travelDataHasImage: true,
      travelTotalCost: 200,
      travelBookingIncludesFlight: true,
      travelBookingIncludesHotel: true,
      travelBookingIncludesTour: true,
    ),
    flightBoardingData: sampleFlightBoardingDataList,
    hotelBookingData: sampleHotelBookingDataList,
    tourBookingData: sampleTourBookingDataList,
  ),
  BookingData(
    bookingId: Random().nextInt(10000),
    bookingFirstName: "flightBookingName",
    bookingLastName: "flightBookingLocation",
    bookingPrice: 340.00,
    bookingPassengers: 3,
    travelData: TravelData(
      travelId: Random().nextInt(10000),
      travelCity: "New York City",
      travelCountry: "USA",
      travelStartDate: DateTime.parse("20260912"),
      travelEndDate: DateTime.parse("20261004"),
      travelImageUrl:
          "https://images.unsplash.com/photo-1758967905380-f62a8c8fd373?&auto=format&fit=crop&q=100&w=1200",
      travelDataHasImage: true,
      travelTotalCost: 200,
      travelBookingIncludesFlight: true,
      travelBookingIncludesHotel: true,
      travelBookingIncludesTour: true,
    ),
    flightBoardingData: sampleFlightBoardingDataList,
    hotelBookingData: sampleHotelBookingDataList,
    tourBookingData: sampleTourBookingDataList,
  ),
  BookingData(
    bookingId: Random().nextInt(10000),
    bookingFirstName: "flightBookingName",
    bookingLastName: "flightBookingLocation",
    bookingPrice: 340.00,
    bookingPassengers: 3,
    travelData: TravelData(
      travelId: Random().nextInt(10000),
      travelCity: "Amsterdam",
      travelCountry: "Netherlands",
      travelStartDate: DateTime.parse("20260912"),
      travelEndDate: DateTime.parse("20261004"),
      travelImageUrl:
          "https://images.unsplash.com/photo-1759512909680-aeb5e7c23671?&auto=format&fit=crop&q=100&w=1200",
      travelDataHasImage: true,
      travelTotalCost: 200,
      travelBookingIncludesFlight: true,
      travelBookingIncludesHotel: true,
      travelBookingIncludesTour: true,
    ),
    flightBoardingData: sampleFlightBoardingDataList,
    hotelBookingData: sampleHotelBookingDataList,
    tourBookingData: sampleTourBookingDataList,
  ),
  BookingData(
    bookingId: Random().nextInt(10000),
    bookingFirstName: "flightBookingName",
    bookingLastName: "flightBookingLocation",
    bookingPrice: 340.00,
    bookingPassengers: 3,
    travelData: TravelData(
      travelId: Random().nextInt(10000),
      travelCity: "Gold Coast City",
      travelCountry: "Australia",
      travelStartDate: DateTime.parse("20260912"),
      travelEndDate: DateTime.parse("20261004"),
      travelImageUrl:
          "https://images.unsplash.com/photo-1759222977064-7a75dc2b83b1?&auto=format&fit=crop&q=100&w=1200",
      travelDataHasImage: true,
      travelTotalCost: 200,
      travelBookingIncludesFlight: true,
      travelBookingIncludesHotel: true,
      travelBookingIncludesTour: true,
    ),
    flightBoardingData: sampleFlightBoardingDataList,
    hotelBookingData: sampleHotelBookingDataList,
    tourBookingData: sampleTourBookingDataList,
  ),
];

final sampleFlightBoardingDataList = [
  FlightBoardingData(
    flightBoardingNumber: Random().nextInt(10000),
    flightPassengerName: "flightBookingName",
    flightBoardingDay: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString().toString(),
    flightBoardingTime: DateTime.parse("20260912"),
    flightDepartureTime: DateTime.parse("20260912"),
    flightArrivalTime: DateTime.parse("20261004"),
    flightOrigin: Airport(airportCode: "", airportCity: ""),
    flightDestination: Airport(airportCode: "", airportCity: ""),
    flightNumber: '#2932231',
    flightPassengerSeat: "PE12",
    flightPassengerClass: "Premium Economy",
    flightDuration: FlightDuration(flightHours: 48, flightMinutes: 23),
    flightGate: "Red",
    flightZone: 2,
    flightPassengers: 3,
  ),
  FlightBoardingData(
    flightBoardingNumber: Random().nextInt(10000),
    flightPassengerName: "flightBookingName",
    flightBoardingDay: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString().toString(),
    flightBoardingTime: DateTime.parse("20260912"),
    flightDepartureTime: DateTime.parse("20260912"),
    flightArrivalTime: DateTime.parse("20261004"),
    flightOrigin: Airport(airportCode: "", airportCity: ""),
    flightDestination: Airport(airportCode: "", airportCity: ""),
    flightNumber: '#2932231',
    flightPassengerSeat: "PE12",
    flightPassengerClass: "Premium Economy",
    flightDuration: FlightDuration(flightHours: 48, flightMinutes: 23),
    flightGate: "Red",
    flightZone: 2,
    flightPassengers: 3,
  ),
  FlightBoardingData(
    flightBoardingNumber: Random().nextInt(10000),
    flightPassengerName: "flightBookingName",
    flightBoardingDay: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString().toString(),
    flightBoardingTime: DateTime.parse("20260912"),
    flightDepartureTime: DateTime.parse("20260912"),
    flightArrivalTime: DateTime.parse("20261004"),
    flightOrigin: Airport(airportCode: "", airportCity: ""),
    flightDestination: Airport(airportCode: "", airportCity: ""),
    flightNumber: '#2932231',
    flightPassengerSeat: "PE12",
    flightPassengerClass: "Premium Economy",
    flightDuration: FlightDuration(flightHours: 48, flightMinutes: 23),
    flightGate: "Red",
    flightZone: 2,
    flightPassengers: 3,
  ),
  FlightBoardingData(
    flightBoardingNumber: Random().nextInt(10000),
    flightPassengerName: "flightBookingName",
    flightBoardingDay: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString().toString(),
    flightBoardingTime: DateTime.parse("20260912"),
    flightDepartureTime: DateTime.parse("20260912"),
    flightArrivalTime: DateTime.parse("20261004"),
    flightOrigin: Airport(airportCode: "", airportCity: ""),
    flightDestination: Airport(airportCode: "", airportCity: ""),
    flightNumber: '#2932231',
    flightPassengerSeat: "PE12",
    flightPassengerClass: "Premium Economy",
    flightDuration: FlightDuration(flightHours: 48, flightMinutes: 23),
    flightGate: "Red",
    flightZone: 2,
    flightPassengers: 3,
  ),
  FlightBoardingData(
    flightBoardingNumber: Random().nextInt(10000),
    flightPassengerName: "flightBookingName",
    flightBoardingDay: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    flightBoardingTime: DateTime.parse("20260912"),
    flightDepartureTime: DateTime.parse("20260912"),
    flightArrivalTime: DateTime.parse("20261004"),
    flightOrigin: Airport(airportCode: "", airportCity: ""),
    flightDestination: Airport(airportCode: "", airportCity: ""),
    flightNumber: '#2932231',
    flightPassengerSeat: "PE12",
    flightPassengerClass: "Premium Economy",
    flightDuration: FlightDuration(flightHours: 48, flightMinutes: 23),
    flightGate: "Red",
    flightZone: 2,
    flightPassengers: 3,
  ),
];

final sampleHotelBookingDataList = [
  HotelBookingData(
    hotelBookingNumber: Random().nextInt(10000),
    guestFullName: "Bill Peterson",
    hotelCheckInTime: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    hotelCheckInDay: DateTime.parse("20260912"),
    hotelCheckOutTime: TimeOfDay.fromDateTime(
      DateTime.parse("20261004"),
    ).toString(),
    hotelCheckOutDay: DateTime.parse("20261004"),
    hotelName: "Cosy Crescent",
    hotelManager: "Alex Rivers",
    hotelFloor: "Third",
    hotelRoomNumber: 21,
  ),
  HotelBookingData(
    hotelBookingNumber: Random().nextInt(10000),
    guestFullName: "Bill Peterson",
    hotelCheckInTime: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    hotelCheckInDay: DateTime.parse("20260912"),
    hotelCheckOutTime: TimeOfDay.fromDateTime(
      DateTime.parse("20261004"),
    ).toString(),
    hotelCheckOutDay: DateTime.parse("20261004"),
    hotelName: "Cosy Crescent",
    hotelManager: "Alex Rivers",
    hotelFloor: "Third",
    hotelRoomNumber: 21,
  ),
  HotelBookingData(
    hotelBookingNumber: Random().nextInt(10000),
    guestFullName: "Bill Peterson",
    hotelCheckInTime: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    hotelCheckInDay: DateTime.parse("20260912"),
    hotelCheckOutTime: TimeOfDay.fromDateTime(
      DateTime.parse("20261004"),
    ).toString(),
    hotelCheckOutDay: DateTime.parse("20261004"),
    hotelName: "Cosy Crescent",
    hotelManager: "Alex Rivers",
    hotelFloor: "Third",
    hotelRoomNumber: 21,
  ),
  HotelBookingData(
    hotelBookingNumber: Random().nextInt(10000),
    guestFullName: "Bill Peterson",
    hotelCheckInTime: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    hotelCheckInDay: DateTime.parse("20260912"),
    hotelCheckOutTime: TimeOfDay.fromDateTime(
      DateTime.parse("20261004"),
    ).toString(),
    hotelCheckOutDay: DateTime.parse("20261004"),
    hotelName: "Cosy Crescent",
    hotelManager: "Alex Rivers",
    hotelFloor: "Third",
    hotelRoomNumber: 21,
  ),
  HotelBookingData(
    hotelBookingNumber: Random().nextInt(10000),
    guestFullName: "Bill Peterson",
    hotelCheckInTime: TimeOfDay.fromDateTime(
      DateTime.parse("20260912"),
    ).toString(),
    hotelCheckInDay: DateTime.parse("20260912"),
    hotelCheckOutTime: TimeOfDay.fromDateTime(
      DateTime.parse("20261004"),
    ).toString(),
    hotelCheckOutDay: DateTime.parse("20261004"),
    hotelName: "Cosy Crescent",
    hotelManager: "Alex Rivers",
    hotelFloor: "Third",
    hotelRoomNumber: 21,
  ),
];

final sampleTourBookingDataList = [
  TourBookingData(
    tourBookingNumber: Random().nextInt(10000),
    fullName: "Peter Sanders",
    tourStartTime: DateTime.parse("20260912"),
    tourDate: TimeOfDay.fromDateTime(DateTime.parse("20260912")).toString(),
    tourEndTime: DateTime.parse("20260912"),
    tourGuideFullName: "tourGuideFullName",
    tourGroup: 1,
    tourLocation: "tourLocation",
    languageInterpreterIncluded: true,
  ),
  TourBookingData(
    tourBookingNumber: Random().nextInt(10000),
    fullName: "Peter Sanders",
    tourStartTime: DateTime.parse("20260912"),
    tourDate: TimeOfDay.fromDateTime(DateTime.parse("20260912")).toString(),
    tourEndTime: DateTime.parse("20260912"),
    tourGuideFullName: "tourGuideFullName",
    tourGroup: 1,
    tourLocation: "tourLocation",
    languageInterpreterIncluded: true,
  ),
  TourBookingData(
    tourBookingNumber: Random().nextInt(10000),
    fullName: "Peter Sanders",
    tourStartTime: DateTime.parse("20260912"),
    tourDate: TimeOfDay.fromDateTime(DateTime.parse("20260912")).toString(),
    tourEndTime: DateTime.parse("20260912"),
    tourGuideFullName: "tourGuideFullName",
    tourGroup: 1,
    tourLocation: "tourLocation",
    languageInterpreterIncluded: true,
  ),
  TourBookingData(
    tourBookingNumber: Random().nextInt(10000),
    fullName: "Peter Sanders",
    tourStartTime: DateTime.parse("20260912"),
    tourDate: TimeOfDay.fromDateTime(DateTime.parse("20260912")).toString(),
    tourEndTime: DateTime.parse("20260912"),
    tourGuideFullName: "tourGuideFullName",
    tourGroup: 1,
    tourLocation: "tourLocation",
    languageInterpreterIncluded: true,
  ),
  TourBookingData(
    tourBookingNumber: Random().nextInt(10000),
    fullName: "Peter Sanders",
    tourStartTime: DateTime.parse("20260912"),
    tourDate: TimeOfDay.fromDateTime(DateTime.parse("20260912")).toString(),
    tourEndTime: DateTime.parse("20260912"),
    tourGuideFullName: "tourGuideFullName",
    tourGroup: 1,
    tourLocation: "tourLocation",
    languageInterpreterIncluded: true,
  ),
];
