# This YAML file configures code generators like build_runner to only work with specific files
# See - https://johnthiriet.com/optimizing-your-flutter-build-runner-for-faster-development/

targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          json: true
        generate_for: # These are the data models that parse data from the Spring Boot back-end
          - lib/data/booking_data.dart
          - lib/data/flight_boarding_data.dart
          - lib/data/hotel_booking_data.dart
          - lib/data/tour_booking_data.dart
          - lib/data/travel_data.dart
          - lib/data/campfire_data.dart
          - lib/data/user_data.dart